--- #YAML:1.0
name:               Bot-WootOff
version:            0.03
abstract:           Poll woot.com during a woot-off and notify via IRC
author:
    - Mike Schilli <cpan@perlmeister.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bot::BasicBot:        0.81
    HTTP::Request::Common:  0
    Log::Log4perl:        1
    POE:                  1
    POE::Component::Client::HTTP:  0
resources:
    repository:  http://github.com/mschilli/bot-wootoff
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
