# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bot-WootOff
version:      0.05
version_from: WootOff.pm
installdirs:  site
requires:
    Bot::BasicBot:                 0.81
    HTTP::Request::Common:         0
    Log::Log4perl:                 1
    POE:                           0.99
    POE::Component::Client::HTTP:  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
